const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1024,height:768}});
 const shell='<html><head></head><body><div id="mainMenu" style="position:absolute;inset:0"><svg id="arc"></svg><svg id="anglePointer"></svg><div id="menuItems">MUSIC NEWS HOME</div><div id="contentArea"><iframe id="preload-mass" src="/mass"></iframe></div></div></body></html>';
 await page.route('**/*',r=>r.request().url().includes('/router/queue')?r.fulfill({json:{current_index:0,tracks:[{id:'1',name:'Playing song',url:'track://1'},{id:'2',name:'Next song',url:'track://2'}]}}):r.fulfill({contentType:'text/html',body:r.request().url().endsWith('/mass')?'<html><body style="margin:0;background:#000"></body></html>':shell}));
 await page.goto('http://bs5c.test');
 await page.addStyleTag({path:path.join(root,'web/styles.css')});
 await page.evaluate(()=>{window.AppConfig={websocket:{input:'ws://invalid'}};window.uiStore={currentRoute:'menu/mass',activeSource:'mass'};window.SourcePresets={mass:{queueOverlay:{playing:true}}};window.LaserPositionMapper={LASER_MAPPING_CONFIG:{MIN_LASER_POS:3,MAX_LASER_POS:123}};});
 for(const name of ['iframe-messenger','media-manager','hardware-input'])await page.addScriptTag({path:path.join(root,`web/js/${name}.js`)});
 await page.evaluate(()=>IframeMessenger.registerIframe('menu/mass','preload-mass'));
 const frame=page.frames().find(f=>f.url().endsWith('/mass'));
 await frame.addStyleTag({path:path.join(root,'web/mood-wheel.css')});
 await frame.addScriptTag({path:path.join(root,'web/js/mood-wheel.js')});
 await frame.evaluate(()=>{window.wheel=new MoodWheel.Wheel({onQueue:()=>parent.postMessage({type:'bs5c-mood-queue'},'*')});window.addEventListener('message',e=>{if(e.data.type==='mood-laser')wheel.laser(e.data.position);if(e.data.type==='button')wheel.button(e.data.button);if(e.data.type==='nav')wheel.nav(e.data.data);});wheel.open();});
 await page.waitForFunction(()=>document.body.classList.contains('mood-wheel-active'));
 for(const id of ['menuItems','arc','anglePointer'])assert.equal(await page.locator('#'+id).evaluate(e=>getComputedStyle(e).visibility),'hidden');
 const box=await page.locator('#preload-mass').boundingBox();assert.equal(box.x,0);assert.equal(box.y,0);assert.equal(box.width,1024);assert.equal(box.height,768);
 await page.evaluate(()=>processLaserEvent({position:93}));await frame.waitForFunction(()=>wheel.state.radius===.75);
 const angle=await frame.evaluate(()=>wheel.state.angle);
 await page.evaluate(()=>handleNavEvent(uiStore,{direction:'clock',speed:1}));await frame.waitForFunction(a=>wheel.state.angle===(a+5)%360,angle);
 await page.evaluate(()=>handleButtonEvent(uiStore,{button:'left'}));await page.waitForSelector('.bs5c-mood-queue-host');await page.waitForFunction(()=>document.querySelector('.bs5c-mood-queue-host').textContent.includes('Playing song'));
 await page.evaluate(()=>handleButtonEvent(uiStore,{button:'right'}));assert.equal(await page.locator('.bs5c-mood-queue-host').count(),0);assert.equal(await frame.locator('.mood-view').count(),1);
 await page.evaluate(()=>handleButtonEvent(uiStore,{button:'right'}));await page.waitForFunction(()=>!document.body.classList.contains('mood-wheel-active'));assert.equal(await frame.locator('.mood-view').count(),0);assert.equal(await page.locator('#menuItems').evaluate(e=>getComputedStyle(e).visibility),'visible');
 await frame.evaluate(()=>wheel.open());await page.waitForFunction(()=>document.body.classList.contains('mood-wheel-active'));
 await page.evaluate(()=>{uiStore.currentRoute='menu/news';document.dispatchEvent(new CustomEvent('bs5c:view-change',{detail:{to:'menu/news'}}));});await page.waitForTimeout(1600);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('mood-wheel-active')),false);
 await browser.close();console.log('Parent iframe integration passed: fullscreen, menu hidden, physical pointer/nav, real queue, Right exit and route cleanup');
})().catch(e=>{console.error(e);process.exit(1)});
