const assert = require('node:assert/strict');
const {normalize,fromPoint,ring} = require('../../../web/js/mood-wheel.js');
assert.equal(fromPoint(0,-1).angle,0);
assert.equal(fromPoint(1,0).angle,90);
assert.equal(fromPoint(0,1).angle,180);
assert.equal(fromPoint(-1,0).angle,270);
assert.equal(fromPoint(2,0).radius,1);
assert.deepEqual(normalize(-5,-1),{angle:355,radius:0});
assert.equal(ring(1/3),'Familiar');
assert.equal(ring(.5),'Blend');
assert.equal(ring(1),'Discover');
// Physical controls preserve angle and select the spatially correct layer.
global.localStorage = {setItem(){}};
const {Wheel, layerMove, mood, discovery} = require('../../../web/js/mood-wheel.js');
const wheel = new Wheel({onPlay(){}});
wheel.state = normalize(90,.25);
wheel.button('right'); assert.equal(wheel.state.radius,.5); assert.equal(wheel.state.angle,90);
wheel.button('right'); assert.equal(wheel.state.radius,5/6);
wheel.button('right'); assert.equal(wheel.state.radius,5/6);
wheel.button('left'); assert.equal(wheel.state.radius,.5);
wheel.state = normalize(270,.25);
wheel.button('left'); assert.equal(wheel.state.radius,.5); assert.equal(wheel.state.angle,270);
wheel.button('right'); assert.equal(wheel.state.radius,1/6);
wheel.laser(123); assert.equal(wheel.state.radius,1/6);
wheel.nav({direction:'clock',speed:1}); assert.equal(wheel.state.angle,275); assert.equal(wheel.state.radius,1/6);
for (const angle of [1,90,179]) assert.equal(layerMove(normalize(angle,.25),'right').radius,.5);
for (const angle of [181,270,359]) assert.equal(layerMove(normalize(angle,.25),'left').radius,.5);
assert.equal(mood(270),'Relaxed'); assert.equal(mood(0),'Bright');
assert.deepEqual([discovery(.25),discovery(.5),discovery(.9)],[0,10,50]);
let closed=false;wheel.close=()=>{closed=true};wheel.button('go_long');assert.equal(closed,true);
console.log('Mood wheel geometry, spatial layers, ignored laser and button routing passed');
